### ISSUE TITLE
New CocoaPods version with latest changes

### ISSUE THREAD

**Issue by ricardopereira** [rvi/msgpack-objective-C#6]
@rvi Could please create a new version in CocoaPods (and a new tag for Carthage) with the macOS support? Thank you

**Comment by ricardopereira** [comment]
BTW, if you need help maintaining this project, I can jump in if you want.

**Comment by rvi** [comment]
I don't use this project anymore, I added you as a contributor, feel free to do the changes you need.

**Comment by ricardopereira** [comment]
🙌 Thanks!

@rvi  Could you add me to the CocoaPod? https://guides.cocoapods.org/making/getting-setup-with-trunk.html#adding-other-people-as-contributors

**Comment by rvi** [comment]
What's your cocoapods email address?

**Comment by ricardopereira** [comment]
@rvi Can you follow me on Twitter so I can DM you? @ricardopereiraw

**Comment by rvi** [comment]
Done, you're a Cocoapods contributor!
